//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoPesaje
    {
        public int idFotoPesaje { get; set; }
        public string ImagenVehiculo { get; set; }
        public int idPesaje { get; set; }
    
        public virtual Pesaje Pesaje { get; set; }
    }
}
