//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenApp2.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Pesaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pesaje()
        {
            this.FotoPesajes = new HashSet<FotoPesaje>();
        }
    
        public int id { get; set; }
        public System.DateTime FechaPesaje { get; set; }
        public string PlacaCamion { get; set; }
        public float Peso { get; set; }
        public string Estacion { get; set; }
        [JsonIgnore]

        public virtual Camion Camion { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotoPesaje> FotoPesajes { get; set; }
    }
}
